import { Router } from 'express';
import PDFDocument from 'pdfkit';
import { insert, find, findOne, update, remove } from '../db.js';
import { requireAuth } from '../middleware/auth.js';

const router = Router();
router.use(requireAuth);

// ---- Secure health record metadata storage ----
router.get('/', async (req, res) => {
  const items = (await find('healthRecords', (r) => r.userId === req.userId))
    .sort((a, b) => new Date(b.date) - new Date(a.date));
  res.json({ records: items });
});

router.post('/', async (req, res) => {
  const { title, type, date, doctor, babyId, notes, attachmentUrl } = req.body || {};
  if (!title) return res.status(400).json({ error: 'title is required' });
  const record = await insert('healthRecords', {
    userId: req.userId, title, type: type || 'document',
    date: date || new Date().toISOString().slice(0, 10),
    doctor, babyId, notes, attachmentUrl,
  });
  res.status(201).json({ record });
});

router.patch('/:id', async (req, res) => {
  const r = await findOne('healthRecords', (x) => x.id === req.params.id && x.userId === req.userId);
  if (!r) return res.status(404).json({ error: 'Not found' });
  res.json({ record: await update('healthRecords', r.id, req.body || {}) });
});

router.delete('/:id', async (req, res) => {
  const r = await findOne('healthRecords', (x) => x.id === req.params.id && x.userId === req.userId);
  if (!r) return res.status(404).json({ error: 'Not found' });
  await remove('healthRecords', r.id);
  res.json({ ok: true });
});

// ---- Export a full health summary as PDF ----
router.get('/export/pdf', async (req, res) => {
  const user = await findOne('users', (u) => u.id === req.userId);
  const records = (await find('healthRecords', (r) => r.userId === req.userId))
    .sort((a, b) => new Date(b.date) - new Date(a.date));
  const babies = await find('babies', (b) => b.userId === req.userId);
  const appointments = await find('appointments', (a) => a.userId === req.userId);

  const doc = new PDFDocument({ margin: 50 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', 'attachment; filename="hajar-health-report.pdf"');
  doc.pipe(res);

  doc.fontSize(22).fillColor('#7C5CBF').text('Hajar Health Report', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#666')
    .text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' })
    .text(`For: ${user?.name || ''} (${user?.email || ''})`, { align: 'center' });
  doc.moveDown();

  const section = (title) => {
    doc.moveDown(0.5).fontSize(15).fillColor('#7C5CBF').text(title);
    doc.moveTo(doc.x, doc.y).lineTo(545, doc.y).strokeColor('#E5DBF5').stroke();
    doc.moveDown(0.3).fillColor('#222').fontSize(11);
  };

  section('Children');
  if (!babies.length) doc.text('No children recorded.');
  babies.forEach((b) => {
    doc.text(`• ${b.name}  —  born ${b.birthDate || 'n/a'}  (${b.deliveryType || 'n/a'})`);
    if (b.birthWeight || b.birthHeight) {
      doc.fillColor('#555').fontSize(10)
        .text(`   Birth weight: ${b.birthWeight || '-'} | Height: ${b.birthHeight || '-'} | Head: ${b.headCircumference || '-'}`)
        .fillColor('#222').fontSize(11);
    }
  });

  section('Appointments');
  if (!appointments.length) doc.text('No appointments recorded.');
  appointments
    .sort((a, b) => new Date(a.datetime) - new Date(b.datetime))
    .forEach((a) => doc.text(`• ${new Date(a.datetime).toLocaleString()} — ${a.title}${a.doctor ? ' (' + a.doctor + ')' : ''}`));

  section('Medical Records');
  if (!records.length) doc.text('No records stored.');
  records.forEach((r) => {
    doc.text(`• [${r.date}] ${r.title} — ${r.type}${r.doctor ? ' / ' + r.doctor : ''}`);
    if (r.notes) doc.fillColor('#555').fontSize(10).text(`   ${r.notes}`).fillColor('#222').fontSize(11);
  });

  doc.moveDown(2).fontSize(8).fillColor('#999')
    .text('This document is generated by the Hajar app for personal record-keeping and is not a medical certificate.', { align: 'center' });

  doc.end();
});

export default router;
